# Generated by Django 3.0 on 2021-10-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=30)),
                ('born', models.CharField(max_length=30)),
                ('birthplace', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('batting_style', models.CharField(max_length=50)),
                ('bowling_style', models.CharField(max_length=50)),
                ('teams', models.TextField()),
                ('total_innings', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('total_avg', models.FloatField()),
                ('total_hundreds', models.IntegerField()),
                ('total_fif', models.IntegerField()),
                ('total_wickets', models.IntegerField()),
                ('total_economy', models.FloatField()),
                ('profile', models.TextField()),
            ],
        ),
    ]
