# Generated by Django 3.0 on 2021-10-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='batting',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='bowling',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
