# Generated by Django 3.0 on 2021-10-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211025_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='batting',
            new_name='batting_avg',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='bowling',
            new_name='bowling_avg',
        ),
    ]
