# Generated by Django 3.0 on 2021-10-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211025_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='img',
            field=models.ImageField(default='NA', upload_to='pic'),
            preserve_default=False,
        ),
    ]
