# Generated by Django 3.0 on 2021-10-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teams_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='role',
            field=models.CharField(choices=[('batsmen', 'Batsmen'), ('bowler', 'Bowler'), ('wk_batsmen', 'Wk_Batsmen'), ('all_rounder', 'All_Rounder')], max_length=50),
        ),
    ]
