# Generated by Django 3.0 on 2021-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211026_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='role',
            field=models.CharField(choices=[('batsmen', 'Batsmen'), ('bowler', 'Bowler'), ('wk_batsmen', 'Wk_Batsmen'), ('batting_all_rounder', 'Batting_All_Rounder'), ('bowling_all_rounder', 'Bowling_All_Rounder')], max_length=50),
        ),
    ]
